[package]
name = "fibonacci-series"
version = "0.1.0"
authors = ["Mohammed Essehemy <mohammedessehemy@gmail.com>"]
edition = "2018"

[lib]
name = "fibonacci_series"
crate-type = ["rlib", "dylib"]

[dependencies]
